services:
  rabbitmq:
    image: harbor.techotakus.cloud/proxy/rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    hostname: rabbitmq
    environment:
      - TZ=Asia/Shanghai
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "0.0.0.0:5672:5672"
      - "0.0.0.0:15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  rabbitmq_data:
  rabbitmq_logs:
